/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Logic.GraphEdge;
import Logic.GraphVertex;
import Logic.Users;
import Logica.DoubleLinkedCircularList;
import Logica.GrafoListaAdyacencia;
import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import java.awt.Image;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author JD101
 */
public class Choose_Type extends javax.swing.JFrame {

    int arrow = 0;
    DoubleLinkedCircularList uberOptions = new DoubleLinkedCircularList();
    private LinkedList<Users> users_o;
    private LinkedList<GraphVertex> listGraphVertex = new LinkedList<>();
    private LinkedList<GraphEdge> listGraphEdge = new LinkedList<>();
    private GrafoListaAdyacencia graphListA = new GrafoListaAdyacencia();
    private Users user_info;

    /**
     * Creates new form ChooseType
     */
    public Choose_Type() {

        initComponents();
        setLocationRelativeTo(null);

        this.uberOptions.add(new ImageIcon(getClass().getResource("/Images/UberTypes/UberComfort.png")).getImage().getScaledInstance(this.labelUberTypesImages.getWidth(), this.getHeight(), Image.SCALE_SMOOTH));
        this.uberOptions.add(new ImageIcon(getClass().getResource("/Images/UberTypes/UberEconomy.png")).getImage().getScaledInstance(this.labelUberTypesImages.getWidth(), this.getHeight(), Image.SCALE_SMOOTH));
        this.uberOptions.add(new ImageIcon(getClass().getResource("/Images/UberTypes/UberXL.png")).getImage().getScaledInstance(this.labelUberTypesImages.getWidth(), this.getHeight(), Image.SCALE_SMOOTH));
        this.uberOptions.add(new ImageIcon(getClass().getResource("/Images/UberTypes/UberYA.png")).getImage().getScaledInstance(this.labelUberTypesImages.getWidth(), this.getHeight(), Image.SCALE_SMOOTH));
        show(this.arrow);

        JL_wallpaper.requestFocus();

    }

    public Choose_Type(Users user, LinkedList<Users> users_o, LinkedList<GraphVertex> listGraphVertex, LinkedList<GraphEdge> listGraphEdge, GrafoListaAdyacencia graphListA) {

        this.user_info = user;
        this.users_o = users_o;
        this.listGraphVertex = listGraphVertex;
        this.listGraphEdge = listGraphEdge;
        this.graphListA = graphListA;

        initComponents();
        setLocationRelativeTo(null);

        this.uberOptions.add(new ImageIcon(getClass().getResource("/Images/UberTypes/UberComfort.png")).getImage().getScaledInstance(this.labelUberTypesImages.getWidth(), this.getHeight(), Image.SCALE_SMOOTH));
        this.uberOptions.add(new ImageIcon(getClass().getResource("/Images/UberTypes/UberEconomy.png")).getImage().getScaledInstance(this.labelUberTypesImages.getWidth(), this.getHeight(), Image.SCALE_SMOOTH));
        this.uberOptions.add(new ImageIcon(getClass().getResource("/Images/UberTypes/UberXL.png")).getImage().getScaledInstance(this.labelUberTypesImages.getWidth(), this.getHeight(), Image.SCALE_SMOOTH));
        this.uberOptions.add(new ImageIcon(getClass().getResource("/Images/UberTypes/UberYA.png")).getImage().getScaledInstance(this.labelUberTypesImages.getWidth(), this.getHeight(), Image.SCALE_SMOOTH));
        show(this.arrow);

        JL_wallpaper.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        JB_accept = new javax.swing.JButton();
        labelNext = new javax.swing.JLabel();
        labelPrevious = new javax.swing.JLabel();
        labelUberTypesImages = new javax.swing.JLabel();
        JB_before = new javax.swing.JButton();
        JL_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 700));
        setResizable(false);

        panelMain.setMaximumSize(new java.awt.Dimension(500, 700));
        panelMain.setMinimumSize(new java.awt.Dimension(500, 700));
        panelMain.setPreferredSize(new java.awt.Dimension(500, 700));
        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB_accept.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        JB_accept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bt_morado.png"))); // NOI18N
        JB_accept.setText(" Aceptar");
        JB_accept.setContentAreaFilled(false);
        JB_accept.setPreferredSize(new java.awt.Dimension(150, 60));
        JB_accept.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bt_naranja.png"))); // NOI18N
        JB_accept.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bt_naranja.png"))); // NOI18N
        JB_accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_acceptActionPerformed(evt);
            }
        });
        panelMain.add(JB_accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, -1, -1));

        labelNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelNextMousePressed(evt);
            }
        });
        panelMain.add(labelNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 250, 500));

        labelPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelPreviousMousePressed(evt);
            }
        });
        panelMain.add(labelPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, 500));

        labelUberTypesImages.setBackground(new java.awt.Color(255, 153, 51));
        labelUberTypesImages.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUberTypesImages.setMaximumSize(new java.awt.Dimension(500, 500));
        labelUberTypesImages.setMinimumSize(new java.awt.Dimension(500, 500));
        labelUberTypesImages.setPreferredSize(new java.awt.Dimension(500, 500));
        panelMain.add(labelUberTypesImages, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        JB_before.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        JB_before.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/regresar_p.png"))); // NOI18N
        JB_before.setText("Regresar");
        JB_before.setContentAreaFilled(false);
        JB_before.setFocusable(false);
        JB_before.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JB_before.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/regresar_p2.png"))); // NOI18N
        JB_before.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/regresar_p2.png"))); // NOI18N
        JB_before.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JB_before.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_beforeActionPerformed(evt);
            }
        });
        panelMain.add(JB_before, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, -1, -1));

        JL_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo_ubers.png"))); // NOI18N
        panelMain.add(JL_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelNextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNextMousePressed

        new Thread();

        try {
            Thread.sleep(300);
        } catch (InterruptedException ex) {
            Logger.getLogger(Choose_Type.class.getName()).log(Level.SEVERE, null, ex);
        }

        int positionX = this.labelUberTypesImages.getX();

        if (positionX > -1) {
            Animacion.Animacion.mover_izquierda(500, 0, 1, 2, this.labelUberTypesImages);
        }

        this.arrow++;

        if (this.arrow >= this.uberOptions.getSize()) {
            this.arrow = 0;
        }

        show(this.arrow);

    }//GEN-LAST:event_labelNextMousePressed

    private void labelPreviousMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPreviousMousePressed

        new Thread();

        try {
            Thread.sleep(300);
        } catch (InterruptedException ex) {
            Logger.getLogger(Choose_Type.class.getName()).log(Level.SEVERE, null, ex);
        }

        int positionX = this.labelUberTypesImages.getX();

        if (positionX > -1) {
            Animacion.Animacion.mover_derecha(-500, 0, 1, 2, this.labelUberTypesImages);
        }

        this.arrow--;

        if (this.arrow < 0) {
            this.arrow = this.uberOptions.getSize() - 1;
        }

        show(this.arrow);

    }//GEN-LAST:event_labelPreviousMousePressed

    private void JB_acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_acceptActionPerformed

        if (this.user_info.getQual() < 4) {

            JOptionPane.showMessageDialog(null, "No se pueden realizar viajes debido a que cuentas con una clificación muy baja.", "", JOptionPane.ERROR_MESSAGE);
            Login login = new Login(this.users_o, this.listGraphVertex, this.listGraphEdge, this.graphListA);
            login.setVisible(true);
            this.dispose();

        } else {

            User_Window user_window = new User_Window(this.user_info, this.users_o, this.listGraphVertex, this.listGraphEdge, this.graphListA);
            user_window.setVisible(true);
            this.dispose();

        }

    }//GEN-LAST:event_JB_acceptActionPerformed

    private void JB_beforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_beforeActionPerformed
        Login login = new Login(this.users_o, this.listGraphVertex, this.listGraphEdge, this.graphListA);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JB_beforeActionPerformed

    public void show(int arrow) {
        Image image = (Image) this.uberOptions.index(arrow);
        this.labelUberTypesImages.setIcon(new ImageIcon(image));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {

            UIManager.setLookAndFeel(new FlatCyanLightIJTheme());

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choose_Type().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_accept;
    private javax.swing.JButton JB_before;
    private javax.swing.JLabel JL_wallpaper;
    private javax.swing.JLabel labelNext;
    private javax.swing.JLabel labelPrevious;
    private javax.swing.JLabel labelUberTypesImages;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
