/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Logica.DoubleLinkedCircularList;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author JD101
 */
public class ChooseType extends javax.swing.JFrame {
    
    int arrow = 0;
    DoubleLinkedCircularList uberOptions = new DoubleLinkedCircularList();

    /**
     * Creates new form ChooseType
     */
    public ChooseType() {
        
        initComponents();
        setLocationRelativeTo(null);
        
        this.uberOptions.add(new ImageIcon(getClass().getResource("/Images/UberTypes/UberComfort.png")).getImage().getScaledInstance(this.labelUberTypesImages.getWidth(), this.getHeight(), Image.SCALE_SMOOTH));
        this.uberOptions.add(new ImageIcon(getClass().getResource("/Images/UberTypes/UberEconomy.png")).getImage().getScaledInstance(this.labelUberTypesImages.getWidth(), this.getHeight(), Image.SCALE_SMOOTH));
        this.uberOptions.add(new ImageIcon(getClass().getResource("/Images/UberTypes/UberXL.png")).getImage().getScaledInstance(this.labelUberTypesImages.getWidth(), this.getHeight(), Image.SCALE_SMOOTH));
        this.uberOptions.add(new ImageIcon(getClass().getResource("/Images/UberTypes/UberYA.png")).getImage().getScaledInstance(this.labelUberTypesImages.getWidth(), this.getHeight(), Image.SCALE_SMOOTH));
        show(this.arrow);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        labelNext = new javax.swing.JLabel();
        labelPrevious = new javax.swing.JLabel();
        labelUberTypesImages = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 700));
        setMinimumSize(new java.awt.Dimension(500, 700));

        panelMain.setMaximumSize(new java.awt.Dimension(500, 700));
        panelMain.setMinimumSize(new java.awt.Dimension(500, 700));
        panelMain.setPreferredSize(new java.awt.Dimension(500, 700));
        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelNextMousePressed(evt);
            }
        });
        panelMain.add(labelNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 250, 500));

        labelPrevious.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelPreviousMousePressed(evt);
            }
        });
        panelMain.add(labelPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, 500));

        labelUberTypesImages.setBackground(new java.awt.Color(255, 153, 51));
        labelUberTypesImages.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUberTypesImages.setMaximumSize(new java.awt.Dimension(500, 500));
        labelUberTypesImages.setMinimumSize(new java.awt.Dimension(500, 500));
        labelUberTypesImages.setPreferredSize(new java.awt.Dimension(500, 500));
        panelMain.add(labelUberTypesImages, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelNextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNextMousePressed
        
        new Thread();
        
        try {
            Thread.sleep(300);
        } catch (InterruptedException ex) {
            Logger.getLogger(ChooseType.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int positionX = this.labelUberTypesImages.getX();
        
        if (positionX > -1) {
            Animacion.Animacion.mover_izquierda(500, 0, 1, 2, this.labelUberTypesImages);
        }
        
        this.arrow++;
        
        if (this.arrow >= this.uberOptions.getSize()) {
            this.arrow = 0;
        }
        
        show(this.arrow);
        
    }//GEN-LAST:event_labelNextMousePressed

    private void labelPreviousMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPreviousMousePressed
        
        new Thread();
        
        try {
            Thread.sleep(300);
        } catch (InterruptedException ex) {
            Logger.getLogger(ChooseType.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int positionX = this.labelUberTypesImages.getX();
        
        if (positionX > -1) {
            Animacion.Animacion.mover_derecha(-500, 0, 1, 2, this.labelUberTypesImages);
        }
        
        this.arrow--;
        
        if (this.arrow < 0) {
            this.arrow = this.uberOptions.getSize() - 1;
        }
        
        show(this.arrow);
        
    }//GEN-LAST:event_labelPreviousMousePressed

    public void show(int arrow) {
        Image image = (Image) this.uberOptions.index(arrow);
        this.labelUberTypesImages.setIcon(new ImageIcon(image));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseType().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelNext;
    private javax.swing.JLabel labelPrevious;
    private javax.swing.JLabel labelUberTypesImages;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
