/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Logic.GraphEdge;
import Logic.GraphVertex;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import Logic.Users;
import Logica.GrafoListaAdyacencia;
import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import java.util.Random;
import javax.swing.UIManager;

/**
 *
 * @author Sara
 */
public class Register extends javax.swing.JFrame {

    LinkedList<Users> users_o;
    private LinkedList<GraphVertex> listGraphVertex = new LinkedList<>();
    private LinkedList<GraphEdge> listGraphEdge = new LinkedList<>();
    private GrafoListaAdyacencia graphListA = new GrafoListaAdyacencia();
    String option_gen;
    int qual_user;

    public Register() {

        initComponents();
        setLocationRelativeTo(null);

    }

    public Register(LinkedList<Users> users_o, LinkedList<GraphVertex> listGraphVertex, LinkedList<GraphEdge> listGraphEdge, GrafoListaAdyacencia graphListA) {

        this.users_o = users_o;
        this.listGraphVertex = listGraphVertex;
        this.listGraphEdge = listGraphEdge;
        this.graphListA = graphListA;

        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        JL_user = new javax.swing.JLabel();
        JT_user = new javax.swing.JTextField();
        JL_password = new javax.swing.JLabel();
        JP_pass = new javax.swing.JPasswordField();
        JL_age = new javax.swing.JLabel();
        JT_age = new javax.swing.JTextField();
        JL_gen = new javax.swing.JLabel();
        RB_o = new javax.swing.JRadioButton();
        RB_h = new javax.swing.JRadioButton();
        RB_m = new javax.swing.JRadioButton();
        JL_card = new javax.swing.JLabel();
        JT_card = new javax.swing.JTextField();
        JL_phone = new javax.swing.JLabel();
        JT_phone = new javax.swing.JTextField();
        JB_before = new javax.swing.JButton();
        JB_checkIn = new javax.swing.JButton();
        JL_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrarse");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL_user.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        JL_user.setText("Usuario:");
        getContentPane().add(JL_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));
        getContentPane().add(JT_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 179, -1));

        JL_password.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        JL_password.setText("Contraseña:");
        getContentPane().add(JL_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));
        getContentPane().add(JP_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 179, -1));

        JL_age.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        JL_age.setText("Edad:");
        getContentPane().add(JL_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));
        getContentPane().add(JT_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 179, -1));

        JL_gen.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        JL_gen.setText("Genero:");
        getContentPane().add(JL_gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        buttonGroup.add(RB_o);
        RB_o.setText("Otro");
        getContentPane().add(RB_o, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        buttonGroup.add(RB_h);
        RB_h.setText("Hombre");
        getContentPane().add(RB_h, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        buttonGroup.add(RB_m);
        RB_m.setText("Mujer");
        getContentPane().add(RB_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        JL_card.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        JL_card.setText("Tarjeta:");
        getContentPane().add(JL_card, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));
        getContentPane().add(JT_card, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 179, -1));

        JL_phone.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        JL_phone.setText("Tel:");
        getContentPane().add(JL_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));
        getContentPane().add(JT_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 179, -1));

        JB_before.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        JB_before.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bt_regresar.png"))); // NOI18N
        JB_before.setText("Regresar");
        JB_before.setContentAreaFilled(false);
        JB_before.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JB_before.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bt_regresar2.png"))); // NOI18N
        JB_before.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JB_before.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_beforeActionPerformed(evt);
            }
        });
        getContentPane().add(JB_before, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 54));

        JB_checkIn.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        JB_checkIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bt_register1.png"))); // NOI18N
        JB_checkIn.setContentAreaFilled(false);
        JB_checkIn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bt_register2_m.png"))); // NOI18N
        JB_checkIn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bt_register2_m.png"))); // NOI18N
        JB_checkIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_checkInActionPerformed(evt);
            }
        });
        getContentPane().add(JB_checkIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        JL_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo_register.png"))); // NOI18N
        getContentPane().add(JL_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_checkInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_checkInActionPerformed
        add_users();
    }//GEN-LAST:event_JB_checkInActionPerformed

    private void JB_beforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_beforeActionPerformed

        Start before = new Start(this.users_o, this.listGraphVertex, this.listGraphEdge, this.graphListA);
        before.setVisible(true);
        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_JB_beforeActionPerformed

    private void add_users() {
        if (JT_user.getText().equals("") || JP_pass.getText().equals("") || JT_age.getText().equals("") || JT_card.getText().equals("") || JT_phone.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingresar los datos solicitados");
        } else {

            option_gender();
            random_numbers_qual();
            //clear the options marked in the radio buttons
            buttonGroup.clearSelection();
            //save user in list
            Users prueba = new Users(JT_user.getText(), JP_pass.getText(), JT_age.getText(), option_gen, JT_card.getText(), JT_phone.getText(), qual_user);
            this.users_o.add(prueba);
            cls();
            //prueba 2
            JOptionPane.showMessageDialog(null, "Usuario agregado");

        }
    }

    //clean the screen
    public void cls() {
        JT_user.setText("");
        JP_pass.setText("");
        JT_age.setText("");
        // jtext_gen.setText("");
        JT_card.setText("");
        JT_phone.setText("");
    }

    //random numbers for user qualification
    private void random_numbers_qual() {
        Random r = new Random();
        qual_user = r.nextInt(5 - 3) + 1;
        qual_user = 5;
    }

    //save radio button option in variable option_gen
    private void option_gender() {
        if (RB_m.isSelected()) {
            option_gen = "Mujer";
        } else if (RB_h.isSelected()) {
            option_gen = "Hombre";
        } else if (RB_o.isSelected()) {
            option_gen = "Otro";
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {

            UIManager.setLookAndFeel(new FlatCyanLightIJTheme());

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_before;
    private javax.swing.JButton JB_checkIn;
    private javax.swing.JLabel JL_age;
    private javax.swing.JLabel JL_card;
    private javax.swing.JLabel JL_gen;
    private javax.swing.JLabel JL_password;
    private javax.swing.JLabel JL_phone;
    private javax.swing.JLabel JL_user;
    private javax.swing.JLabel JL_wallpaper;
    private javax.swing.JPasswordField JP_pass;
    private javax.swing.JTextField JT_age;
    private javax.swing.JTextField JT_card;
    private javax.swing.JTextField JT_phone;
    private javax.swing.JTextField JT_user;
    private javax.swing.JRadioButton RB_h;
    private javax.swing.JRadioButton RB_m;
    private javax.swing.JRadioButton RB_o;
    private javax.swing.ButtonGroup buttonGroup;
    // End of variables declaration//GEN-END:variables
}
