/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;


/**
 *
 * @author Sara
 */
public class User_information extends javax.swing.JFrame {

    /**
     * Creates new form User_information
     */
    public User_information() {
        initComponents();
        setLocationRelativeTo(null);
        information_user();
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_age = new javax.swing.JLabel();
        JL_gen = new javax.swing.JLabel();
        JL_phone = new javax.swing.JLabel();
        JL_qual = new javax.swing.JLabel();
        JB_before = new javax.swing.JButton();
        JL_user = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informacion");
        setBackground(new java.awt.Color(0, 0, 204));
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL_age.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        JL_age.setForeground(new java.awt.Color(73, 0, 153));
        JL_age.setText("Edad:");
        getContentPane().add(JL_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        JL_gen.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        JL_gen.setForeground(new java.awt.Color(73, 0, 153));
        JL_gen.setText("Genero:");
        getContentPane().add(JL_gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        JL_phone.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        JL_phone.setForeground(new java.awt.Color(73, 0, 153));
        JL_phone.setText("Tel:");
        getContentPane().add(JL_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        JL_qual.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        JL_qual.setForeground(new java.awt.Color(73, 0, 153));
        JL_qual.setText("Calificacion");
        getContentPane().add(JL_qual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        JB_before.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        JB_before.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bt_regresar.png"))); // NOI18N
        JB_before.setText("Regresar");
        JB_before.setContentAreaFilled(false);
        JB_before.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JB_before.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bt_regresar2.png"))); // NOI18N
        JB_before.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JB_before.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_beforeActionPerformed(evt);
            }
        });
        getContentPane().add(JB_before, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        JL_user.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        JL_user.setForeground(new java.awt.Color(73, 0, 153));
        JL_user.setText("Usuario:");
        getContentPane().add(JL_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo_information_user.png"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited

    }//GEN-LAST:event_formMouseExited

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered

    }//GEN-LAST:event_formMouseEntered

    private void JB_beforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_beforeActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_JB_beforeActionPerformed
    private void information_user() {
        //show user information in labels
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_before;
    private javax.swing.JLabel JL_age;
    private javax.swing.JLabel JL_gen;
    private javax.swing.JLabel JL_phone;
    private javax.swing.JLabel JL_qual;
    private javax.swing.JLabel JL_user;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
