/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Logic.Users;
import javax.swing.JFrame;

/**
 *
 * @author Sara
 */
public class User_information extends javax.swing.JFrame {

    //Attributes
    Users user_info;

    /**
     * Creates new form User_information
     */
    public User_information() {
        initComponents();
        setLocationRelativeTo(null);
        information_user();
    }

    public User_information(Users user) {
        initComponents();
        setLocationRelativeTo(null);
        this.user_info = user;
        information_user();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_age = new javax.swing.JLabel();
        JL_gen = new javax.swing.JLabel();
        JL_phone = new javax.swing.JLabel();
        JL_qual = new javax.swing.JLabel();
        JB_before = new javax.swing.JButton();
        JL_user = new javax.swing.JLabel();
        JL_user_name = new javax.swing.JLabel();
        JL_user_age = new javax.swing.JLabel();
        JL_user_gen = new javax.swing.JLabel();
        JL_user_phone = new javax.swing.JLabel();
        JL_user_qual = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informacion");
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(330, 410));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        getContentPane().setLayout(null);

        JL_age.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        JL_age.setForeground(new java.awt.Color(227, 203, 252));
        JL_age.setText("Edad");
        getContentPane().add(JL_age);
        JL_age.setBounds(20, 80, 43, 22);

        JL_gen.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        JL_gen.setForeground(new java.awt.Color(227, 203, 252));
        JL_gen.setText("Genero");
        getContentPane().add(JL_gen);
        JL_gen.setBounds(20, 140, 62, 22);

        JL_phone.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        JL_phone.setForeground(new java.awt.Color(227, 203, 252));
        JL_phone.setText("Tel");
        getContentPane().add(JL_phone);
        JL_phone.setBounds(20, 200, 25, 22);

        JL_qual.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        JL_qual.setForeground(new java.awt.Color(227, 203, 252));
        JL_qual.setText("Calificacion");
        getContentPane().add(JL_qual);
        JL_qual.setBounds(20, 260, 97, 22);

        JB_before.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        JB_before.setForeground(new java.awt.Color(255, 255, 255));
        JB_before.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bt_regresar.png"))); // NOI18N
        JB_before.setText("Regresar");
        JB_before.setContentAreaFilled(false);
        JB_before.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JB_before.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bt_regresar2.png"))); // NOI18N
        JB_before.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JB_before.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_beforeActionPerformed(evt);
            }
        });
        getContentPane().add(JB_before);
        JB_before.setBounds(90, 310, 120, 80);

        JL_user.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        JL_user.setForeground(new java.awt.Color(227, 203, 252));
        JL_user.setText("Usuario");
        getContentPane().add(JL_user);
        JL_user.setBounds(20, 20, 63, 22);

        JL_user_name.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        JL_user_name.setForeground(new java.awt.Color(31, 0, 87));
        JL_user_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JL_user_name.setMaximumSize(new java.awt.Dimension(190, 20));
        JL_user_name.setMinimumSize(new java.awt.Dimension(190, 20));
        JL_user_name.setPreferredSize(new java.awt.Dimension(190, 20));
        getContentPane().add(JL_user_name);
        JL_user_name.setBounds(140, 20, 190, 20);

        JL_user_age.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        JL_user_age.setForeground(new java.awt.Color(31, 0, 87));
        JL_user_age.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JL_user_age.setMaximumSize(new java.awt.Dimension(190, 20));
        JL_user_age.setMinimumSize(new java.awt.Dimension(190, 20));
        JL_user_age.setPreferredSize(new java.awt.Dimension(190, 20));
        getContentPane().add(JL_user_age);
        JL_user_age.setBounds(140, 80, 190, 20);

        JL_user_gen.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        JL_user_gen.setForeground(new java.awt.Color(31, 0, 87));
        JL_user_gen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JL_user_gen.setMaximumSize(new java.awt.Dimension(190, 20));
        JL_user_gen.setMinimumSize(new java.awt.Dimension(190, 20));
        JL_user_gen.setPreferredSize(new java.awt.Dimension(190, 20));
        getContentPane().add(JL_user_gen);
        JL_user_gen.setBounds(130, 140, 190, 20);

        JL_user_phone.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        JL_user_phone.setForeground(new java.awt.Color(31, 0, 87));
        JL_user_phone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JL_user_phone.setMaximumSize(new java.awt.Dimension(190, 20));
        JL_user_phone.setMinimumSize(new java.awt.Dimension(190, 20));
        JL_user_phone.setPreferredSize(new java.awt.Dimension(190, 20));
        getContentPane().add(JL_user_phone);
        JL_user_phone.setBounds(140, 200, 190, 20);

        JL_user_qual.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        JL_user_qual.setForeground(new java.awt.Color(31, 0, 87));
        JL_user_qual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JL_user_qual.setMaximumSize(new java.awt.Dimension(190, 20));
        JL_user_qual.setMinimumSize(new java.awt.Dimension(190, 20));
        JL_user_qual.setPreferredSize(new java.awt.Dimension(190, 20));
        getContentPane().add(JL_user_qual);
        JL_user_qual.setBounds(140, 260, 190, 20);

        wallpaper.setBackground(new java.awt.Color(54, 0, 255));
        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo_information_user.png"))); // NOI18N
        wallpaper.setMaximumSize(new java.awt.Dimension(330, 410));
        wallpaper.setMinimumSize(new java.awt.Dimension(330, 410));
        wallpaper.setPreferredSize(new java.awt.Dimension(330, 410));
        getContentPane().add(wallpaper);
        wallpaper.setBounds(0, 0, 330, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited

    }//GEN-LAST:event_formMouseExited

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered

    }//GEN-LAST:event_formMouseEntered

    private void JB_beforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_beforeActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_JB_beforeActionPerformed
    private void information_user() {
        //show user information in labels
        this.JL_user_name.setText(this.user_info.getUser());
        this.JL_user_age.setText(this.user_info.getAge());
        this.JL_user_gen.setText(this.user_info.getGender());
        this.JL_user_phone.setText(this.user_info.getPhone());
        this.JL_user_qual.setText(Integer.toString(this.user_info.getQual()));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_before;
    private javax.swing.JLabel JL_age;
    private javax.swing.JLabel JL_gen;
    private javax.swing.JLabel JL_phone;
    private javax.swing.JLabel JL_qual;
    private javax.swing.JLabel JL_user;
    private javax.swing.JLabel JL_user_age;
    private javax.swing.JLabel JL_user_gen;
    private javax.swing.JLabel JL_user_name;
    private javax.swing.JLabel JL_user_phone;
    private javax.swing.JLabel JL_user_qual;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
